package accounts;
/**
* @author Duc Linh
*/
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import javafx.stage.Stage;
import login.DBConnect;

import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ResourceBundle;
import javafx.event.ActionEvent;
import javafx.scene.control.Label;

import javafx.scene.control.TextArea;

import javafx.scene.control.PasswordField;

import javafx.scene.control.ChoiceBox;

public class AddOrModController implements Initializable{
	
	@FXML
	private Label lbTitle;
	@FXML
	private Label lbUsername;
	@FXML
	private Label lbPass;
	@FXML
	private Label lbConfirmPass;
	@FXML
	private Label lbPermission;
	@FXML
    private Label lbStatus;
	@FXML
	private Label lbDescription;
	@FXML
	private TextField txtUsername;
	@FXML
	private PasswordField txtPass;
	@FXML
	private PasswordField txtConfirmPass;
	@FXML
	private ChoiceBox<Integer> choiceOption1;
	@FXML
	private ChoiceBox<String> choiceOption2;
	@FXML
	private TextArea txtDecs;
	@FXML
	private Label lbMessage;
	@FXML
	private Button btnConfirmAdd;
	@FXML
	private Button btnClear;

	// Event Listener on Button[#btnConfirmAdd].onAction
	@FXML
	public void handleAddModAcc(ActionEvent event) throws SQLException {
		Button btn = (Button)event.getSource();
		if(btn.getText().equals("Create")) {
			addAccount();
			
		}
		if(btn.getText().equals("Update")) {
			updateAccount();
		}
		// TODO Autogenerated
	}
	Connection cnn;
    String user ="sa";
    String password="123";
    String database= "MyApps";
    String tablename ="user";
    PreparedStatement st;
    ResultSet rs;
	ItemAcc ac;
	boolean option;
	Integer[] option1 = {2,3};
	Integer[] option2 = {3};
	String[] optS ={"Active","Block"};
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		

	}
	//Nhận data từ thằng AccountsController truyền qua.
	//Nếu option = false thì chạy phần AddNew
	//Nếu option = true thì chạy phần Update
	public void setData(ItemAcc ac,int permission,boolean option) throws SQLException {
		this.ac = ac;
		this.option = option;
		if(option) {
			//Update phan tu Account
			lbTitle.setText("UPDATE INFORMATION OF ACCOUNT");
			btnConfirmAdd.setText("Update");
			txtUsername.setText(ac.username);
			txtUsername.setEditable(false);
			txtPass.setText(ac.getPassword());
			txtConfirmPass.setText(ac.getPassword());
			txtDecs.setText(ac.desc);
			if(permission==1) {
				choiceOption1.getItems().addAll(option1);
				choiceOption1.setValue(ac.permission);
				choiceOption2.getItems().addAll(optS);
				choiceOption2.setValue(ac.status);
			}else {
				choiceOption1.getItems().addAll(option2);
				choiceOption2.getItems().addAll(ac.status);
			}
			
			
		}else {
			if(permission==1) {
				choiceOption1.getItems().addAll(option1);
				choiceOption2.getItems().addAll(optS);
			}else if(permission==2) {
				choiceOption1.getItems().addAll(option2);
				choiceOption2.getItems().addAll(optS);
			}
			
		}
		

	}
	private void addAccount() throws SQLException {
		String query = "insert into [user] values(?,?,?,?,?)";
		cnn = DBConnect.makeConnection(user, password, database);
		st =cnn.prepareStatement(query);
		st.setString(1, txtUsername.getText());
		st.setString(2, txtPass.getText());
		st.setInt(3, choiceOption1.getValue());
		st.setString(4, choiceOption2.getValue());
		st.setString(5, txtDecs.getText());
		int count = st.executeUpdate();
		if(count ==0) {
			Alert alert = new Alert(AlertType.ERROR);
			alert.setTitle("Error Message");
			alert.setContentText("Has been Error, Can not add new Account!");
			alert.show();
			
		}else {
			Alert alert = new Alert(AlertType.INFORMATION);
			alert.setTitle("Successfuly");
			alert.setContentText("Registration Completed Successfully!");
			alert.showAndWait();
			Stage stage = (Stage)lbTitle.getScene().getWindow();
			stage.close();
		}
	}
	private void updateAccount() throws SQLException {
		String query = "  update [user] set password=?, permission=?, status=?, description=?"
				+ " where username=?";
		cnn = DBConnect.makeConnection(user, password, database);
		st =cnn.prepareStatement(query);
		st.setString(5, txtUsername.getText());
		st.setString(1, txtPass.getText());
		st.setInt(2, choiceOption1.getValue());
		st.setString(3, choiceOption2.getValue());
		st.setString(4, txtDecs.getText());
		int count = st.executeUpdate();
		if(count ==0) {
			Alert alert = new Alert(AlertType.ERROR);
			alert.setTitle("Error Message");
			alert.setContentText("Has been Error, Can not Update Account!");
			alert.show();
			
		}else {
			Alert alert = new Alert(AlertType.INFORMATION);
			alert.setTitle("Successfuly");
			alert.setContentText("Update Completed Successfully!");
			alert.showAndWait();
			Stage stage = (Stage)lbTitle.getScene().getWindow();
			stage.close();
		}
	}
	
}
